### ISSUE TITLE
File not found: 'exp/dygan_vc/dygan_vc_vq_spkemb/epoch_100.pth'

### ISSUE THREAD

**Issue by mrlament** [MingjieChen/DYGANVC#11]
I'm getting a file not found error when I run 

> python inference.py

it returns:

> FileNotFoundError: [Errno 2] No such file or directory: 'exp/dygan_vc/dygan_vc_vq_spkemb/epoch_100.pth

I've searched but can't find where to get those files. Any guidance?

**Comment by MingjieChen** [comment]
This is the pretrained model weights, which I did not upload.
I will upload the pretrained model weights, but need some time. 
The training is just several hours, you can train the model, if you are urgent.

**Comment by mrlament** [comment]
Thanks so much! Got it sorted.
