### ISSUE TITLE
extract_speaker_embed.sh returns an error: "ValueError: Improper number of dimensions to norm."

### ISSUE THREAD

**Issue by mrlament** [MingjieChen/DYGANVC#12]
I'm at Step 5. of the "How to Run" process from the main Git page, and I'm getting an error.  Here is my output when I execute 

`./extract_speaker_embed.sh`

It returns:

> 
> ./extract_speaker_embed.sh: line 5: activate: No such file or directory
> Loaded the voice encoder model on cpu in 0.09 seconds.
> SpeakerEncoder(
>   (lstm): LSTM(40, 256, num_layers=3, batch_first=True)
>   (linear): Linear(in_features=256, out_features=256, bias=True)
>   (relu): ReLU()
> )
> encoder
> The number of parameters: 1423616
> /home/lhill/anaconda3/envs/torch_1.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
>   out=out, **kwargs)
> /home/lhill/anaconda3/envs/torch_1.7/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> Traceback (most recent call last):
>   File "extract_speaker_embed.py", line 31, in <module>
>     spk_emb = encoder.embed_speaker(audios)
>   File "/mnt/w/python stuff/dyganvc/speaker_encoder/voice_encoder.py", line 173, in embed_speaker
>     return raw_embed / np.linalg.norm(raw_embed, 2)
>   File "<__array_function__ internals>", line 6, in norm
>   File "/home/lhill/anaconda3/envs/torch_1.7/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 2611, in norm
>     raise ValueError("Improper number of dimensions to norm.")
> ValueError: Improper number of dimensions to norm.
>

**Comment by MingjieChen** [comment]
sorry, I couldn't reproduce this error.

**Comment by mrlament** [comment]
Okay. Thank you for trying!
