### ISSUE TITLE
Why not train like StarGAN

### ISSUE THREAD

**Issue by ywh-my** [MingjieChen/DYGANVC#13]
StarGAN training way could keep a many-to-many  VC, why do you only use identity loss while lacking of consistent loss?
And , is identity loss  necessary in StarGAN training? 
Thank you .

**Comment by MingjieChen** [comment]
Hello,

I tried to use cycle-consistency loss as StarGAN, actually it made worse performance.

**Comment by ywh-my** [comment]
Dear chen, I would like to get your help。I use the losses like your DYGAN VC , including G_adv loss, identity loss , to train a emotional conversion framework. (using GST as emotional encoder , and I have a generator  and discriminator . )

But I found that the convergence model could only reconstruct the input , but This model does not have the ability to change styles. (The output mel looks like the same as the input mel)

I do not know how to get a model that has style transfer ability?

**Comment by MingjieChen** [comment]
Hello,

This model is specifically developed for changing speaker identity. I don't think it will work for emotional transfer.

**Comment by ywh-my** [comment]
Thank you
