### ISSUE TITLE
What do these indices mean?

### ISSUE THREAD

**Issue by ZJ-CAI** [MingjieChen/DYGANVC#9]
When training, real:0.32081  fake:0.19402  reg:0.00009  adv:0.30563  id:0.30306, these indices make me confused.
Would you please show me which one(s) is relative to the performance of the generator model? Thank you

**Comment by MingjieChen** [comment]
Hello, the 'id' here means identity reconstruction loss, which is a MAE loss with the groundtruth mel spectrograms.

**Comment by ZJ-CAI** [comment]
> Hello, the 'id' here means identity reconstruction loss, which is a MAE loss with the groundtruth mel spectrograms.



> Hello, the 'id' here means identity reconstruction loss, which is a MAE loss with the groundtruth mel spectrograms.

Thanks for your reply!
